apiVersion: v1
kind: Service
metadata:
  name: gnn-service
  namespace: fraud-detection
  labels:
    app: gnn-service
    group-id: hp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: gnn-service
    group-id: hp
  sessionAffinity: None
